name: DeployAzureFunction
variables:
  FunctionAppName: '4besDay16'
  AzureConnection: 'MSDN'
  ResourcegGroupName: '4besDay16'

trigger:
  branches:
    include:
    - 'master' 

stages:

- stage: Build
  jobs:
  - job: Test_FA
    pool:
      vmImage: windows-2019
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Test ARM Deployment'
      inputs:
        azureSubscription: $(AzureConnection)
        resourceGroupName: $(ResourcegGroupName)
        location: 'west Europe'
        csmFile: Daya16Posadas/Deployment/azuredeploy.json
        deploymentMode: Validation
    - powershell: |
        $Alldata = Import-CSV $(Build.SourcesDirectory)/Daya16Posadas/Locations.CSV
        $AllDataHTML = $AllData | ConvertTo-Html
        $Script = Get-Content "$(Build.SourcesDirectory)/Daya16Posadas/Deployment/SourceScript.ps1"
        Write-Output "script $Script"
        $NewScript = $Script -replace 'PlaceHolder', "$AlldataHTML"
        $NewScript | Out-File "$(Build.SourcesDirectory)/Daya16Posadas/FunctionApp/Get-Location/run.ps1" -force
      displayName: 'Create new Function File with CSV'

  - job: Build_FA
    dependsOn:
      Test_FA
    pool:
      vmImage: windows-2019
    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive FunctionApp'
      inputs:
        rootFolderOrFile: $(Build.SourcesDirectory)/Daya16Posadas/FunctionApp
        includeRootFolder: false
        archiveFile: '$(System.DefaultWorkingDirectory)/zip/FunctionApp.zip'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'zip'
        targetPath: '$(System.DefaultWorkingDirectory)/zip'

- stage: Deploy
  condition:
    and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn:
    Build
  jobs:
  - job: Deploy_ARM
    pool:
      vmImage: windows-2019
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Deploy Azure Resources'
      inputs:
        azureSubscription: $(AzureConnection)
        resourceGroupName: $(ResourcegGroupName)
        location: 'West Europe'
        csmFile: Daya16Posadas/Deployment/azuredeploy.json
        csmParametersFile: Daya16Posadas/Deployment/azuredeploy.parameters.json
        overrideParameters: '-functionAppName $(FunctionAppName)'
        deploymentMode: Incremental
        deploymentOutputs: DeploymentOutput
  - job: Deploy_FA
    dependsOn:
      Deploy_ARM
    pool:
      vmImage: windows-2019
    steps:
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'zip'
        targetPath: '$(System.DefaultWorkingDirectory)/zip'
    - task: AzureFunctionApp@1
      displayName: 'Deploy Azure Function'
      inputs:
        azureSubscription: $(AzureConnection)
        appType: functionApp
        appName: $(FunctionAppName)
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        deploymentMethod: 'auto'
