name: DeployAzureFunction
variables:
  FunctionAppName: '4besDay16'
  AzureConnection: 'MSDN'
  ResourcegGroupName: '4besDay16'

trigger:
  branches:
    include:
    - 'Master'  # must quote since "*" is a YAML reserved character; we want a string

stages:

- stage: Build
  jobs:
  - job: Test_FA
    pool:
      vmImage: windows-2019
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Test ARM Deployment'
      inputs:
        azureSubscription: $(AzureConnection)
        resourceGroupName: $(ResourcegGroupName)
        location: 'west Europe'
        csmFile: Deployment/azuredeploy.json
        deploymentMode: Validation
    - powershell: |
        $AlldataHTML = "(Import-Csv $(Build.SourcesDirectory)/Locations.CSV)" | ConvertTo-Html
        $Script = Get-Content "$(Build.SourcesDirectory)/SourceScript.ps1"
        $NewScript = $script -replace 'PlaceHolder', "$AlldataHTML"
        $NewScript | Out-File "$(Build.SourcesDirectory)/FunctionApp/Get-Location\run.ps1"
      displayName: 'Create new Function File with CSV'
  - job: Build_FA
    pool:
      vmImage: windows-2019
    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive FunctionApp'
      inputs:
        rootFolderOrFile: FunctionApp
        includeRootFolder: false
        archiveFile: '$(System.DefaultWorkingDirectory)/zip/FunctionApp.zip'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'zip'
        targetPath: '$(System.DefaultWorkingDirectory)/zip'

- stage: Deploy
  condition:
    and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn:
    Build
  jobs:
  - job: Deploy_ARM
    pool:
      vmImage: windows-2019
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Deploy Azure Resources'
      inputs:
        azureSubscription: $(AzureConnection)
        resourceGroupName: $(ResourcegGroupName)
        location: 'West Europe'
        csmFile: Deployment/azuredeploy.json
        csmParametersFile: Deployment/azuredeploy.parameters.json
        overrideParameters: '-functionAppName $(FunctionAppName)'
        deploymentMode: Incremental
        deploymentOutputs: DeploymentOutput
  - job: Deploy_FA
    dependsOn:
      Deploy_ARM
    pool:
      vmImage: windows-2019
    steps:
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'zip'
        targetPath: '$(System.DefaultWorkingDirectory)/zip'
    - task: AzureFunctionApp@1
      displayName: 'Deploy Azure Function'
      inputs:
        azureSubscription: $(AzureConnection)
        appType: functionApp
        appName: $(FunctionAppName)
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        deploymentMethod: 'auto'
